const products = [
{id:1,name:"LIGOZZA Classic Tee",price:2500,cat:"Men",img:"assets/MEN 1.png",gallery:["assets/MEN 1.png","assets/MEN 1.png"],sizes:["S","M","L","XL","XXL"],desc:"Premium cotton tee with a clean LIGOZZA finish. Comfortable, versatile and made for everyday style."},
{id:2,name:"LIGOZZA Hoodie",price:4500,cat:"Men",img:"assets/MEN 2.png",gallery:["assets/MEN 2.png","assets/MEN 2.png"],sizes:["S","M","L","XL","XXL"],desc:"Soft everyday hoodie with a relaxed silhouette and premium streetwear feel."},
{id:3,name:"LIGOZZA Oversized Tee",price:3200,cat:"Men",img:"assets/MEN 3.png",gallery:["assets/MEN 3.png","assets/MEN 3.png"],sizes:["S","M","L","XL","XXL"],desc:"Oversized fit with an effortless modern profile."},
{id:4,name:"LIGOZZA Cargo Pants",price:4300,cat:"Men",img:"assets/MEN 4.png",gallery:["assets/MEN 4.png","assets/MEN 4.png"],sizes:["S","M","L","XL","XXL"],desc:"Utility-inspired cargo pants designed for movement and comfort."},

{id:5,name:"LIGOZZA Dress",price:4500,cat:"Women",img:"assets/WOMEN 1.png",gallery:["assets/WOMEN 1.png","assets/WOMEN 1.png"],sizes:["S","M","L","XL","XXL"],desc:"A modern statement dress designed for an elegant everyday look."},
{id:6,name:"LIGOZZA Top",price:2800,cat:"Women",img:"assets/WOMEN 2.png",gallery:["assets/WOMEN 2.png","assets/WOMEN 2.png"],sizes:["S","M","L","XL","XXL"],desc:"Minimal top with a flattering modern silhouette."},
{id:7,name:"LIGOZZA Jeans",price:3900,cat:"Women",img:"assets/WOMEN 3.png",gallery:["assets/WOMEN 3.png","assets/WOMEN 3.png"],sizes:["S","M","L","XL","XXL"],desc:"Versatile denim with a clean contemporary fit."},
{id:8,name:"LIGOZZA Jacket",price:5200,cat:"Women",img:"assets/WOMEN 4.png",gallery:["assets/WOMEN 4.png","assets/WOMEN 4.png"],sizes:["S","M","L","XL","XXL"],desc:"Layer-ready jacket with a refined streetwear aesthetic."},

{id:9,name:"LIGOZZA Cap",price:1800,cat:"Accessories",img:"assets/tee.svg",gallery:["assets/tee.svg","assets/tee.svg"],sizes:["One Size"],desc:"Everyday LIGOZZA cap with an adjustable fit."},
{id:10,name:"LIGOZZA Sunglasses",price:2500,cat:"Accessories",img:"assets/hoodie.svg",gallery:["assets/hoodie.svg","assets/hoodie.svg"],sizes:["One Size"],desc:"Minimal sunglasses made to finish your look."},
{id:11,name:"LIGOZZA Watch",price:6000,cat:"Accessories",img:"assets/cap.svg",gallery:["assets/cap.svg","assets/cap.svg"],sizes:["One Size"],desc:"Clean dial and versatile styling for everyday wear."},
{id:12,name:"LIGOZZA Bag",price:3200,cat:"Accessories",img:"assets/bag.svg",gallery:["assets/bag.svg","assets/bag.svg"],sizes:["One Size"],desc:"Compact carry-all with a modern LIGOZZA aesthetic."},

{id:13,name:"LIGOZZA New Tee",price:2900,cat:"New Arrivals",img:"assets/NEW.png",gallery:["assets/NEW.png","assets/NEW.png"],sizes:["S","M","L","XL","XXL"],desc:"Fresh-season tee from the latest LIGOZZA drop."},
{id:14,name:"LIGOZZA Sweater",price:4200,cat:"New Arrivals",img:"assets/NEW 2.png",gallery:["assets/NEW 1.png","assets/NEW 1.png"],sizes:["S","M","L","XL","XXL"],desc:"New-season sweater built for easy layering."},
{id:15,name:"LIGOZZA Denim",price:4800,cat:"New Arrivals",img:"assets/watch.svg",gallery:["assets/watch.svg","assets/watch.svg"],sizes:["S","M","L","XL","XXL"],desc:"Fresh denim with a contemporary cut."},
{id:16,name:"LIGOZZA Shades",price:2200,cat:"New Arrivals",img:"assets/sneakers.svg",gallery:["assets/sneakers.svg","assets/sneakers.svg"],sizes:["One Size"],desc:"New accessory drop with a sleek finish."}
];
function normalizeProducts(arr){return (arr||[]).map(p=>({...p,gallery:(Array.isArray(p.gallery)&&p.gallery.length?p.gallery:[p.img]).filter(Boolean),sizes:(Array.isArray(p.sizes)&&p.sizes.length?p.sizes:(p.cat==="Accessories"?["One Size"]:["S","M","L","XL","XXL"]))}))}
function loadData(){const saved=JSON.parse(localStorage.getItem("ligozza_products")||"null");return normalizeProducts(saved||products)}
function saveData(d){localStorage.setItem("ligozza_products",JSON.stringify(normalizeProducts(d)))}
function cart(){return JSON.parse(localStorage.getItem("ligozza_cart")||"[]")}
function saveCart(c){localStorage.setItem("ligozza_cart",JSON.stringify(c));updateCount()}
function addToCart(id,size="",qty=1){let c=cart();let key=`${id}__${size||"One Size"}`;let x=c.find(i=>i.key===key);if(x)x.qty+=qty;else c.push({id,qty,key,size:size||"One Size"});saveCart(c);toast("Added to cart")}
function changeQty(key,n){let c=cart();let x=c.find(i=>i.key===key);if(!x)return;x.qty+=n;if(x.qty<1)c=c.filter(i=>i.key!==key);saveCart(c);renderCart()}
function updateCount(){let n=cart().reduce((a,b)=>a+b.qty,0);document.querySelectorAll(".cart-count").forEach(x=>x.textContent=n)}
function money(n){return "Rs. "+Number(n).toLocaleString("en-LK")}
function toast(t){let e=document.createElement("div");e.textContent=t;e.style="position:fixed;right:20px;bottom:20px;background:#0b0d0f;color:white;padding:14px 18px;border-radius:12px;z-index:100";document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
function card(p){return `<article class="card"><a href="product.html?id=${p.id}"><img src="${p.img}" alt="${p.name}"></a><div class="pad"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="muted">${p.cat}</div><a class="btn" href="product.html?id=${p.id}">View Product</a></div></article>`}
function renderGrid(list,el){if(!el)return;el.innerHTML=list.map(card).join("")}
function openDrawer(){document.querySelector(".drawer")?.classList.add("open")}
function closeDrawer(){document.querySelector(".drawer")?.classList.remove("open")}
function renderCart(){let el=document.querySelector("#cart-list");if(!el)return;let ps=loadData(),c=cart();if(!c.length){el.innerHTML="<p>Your cart is empty. <a href='shop.html'><b>Continue shopping →</b></a></p>";let s=document.querySelector("#summary");if(s)s.innerHTML="";return}el.innerHTML=c.map(i=>{let p=ps.find(x=>x.id==i.id);if(!p)return"";return `<div class="cartrow"><img src="${p.img}"><div><b>${p.name}</b><div class="muted">${money(p.price)} each · Size: ${i.size||"One Size"}</div></div><div><button onclick="changeQty('${i.key}',-1)">−</button> ${i.qty} <button onclick="changeQty('${i.key}',1)">+</button></div><div class="lineprice">${money(p.price*i.qty)}</div></div>`}).join("");let sub=c.reduce((a,i)=>{let p=ps.find(p=>p.id==i.id);return a+(p?p.price*i.qty:0)},0);document.querySelector("#summary").innerHTML=`<div><span>Subtotal</span><b>${money(sub)}</b></div><div><span>Shipping</span><span>${sub>=5000?"Free":money(500)}</span></div><div class="total"><span>Total</span><span>${money(sub+(sub>=5000?0:500))}</span></div><button class="btn" style="width:100%;margin-top:15px" onclick="toast('Checkout demo — connect your payment gateway here')">Proceed to Checkout</button>`}
function renderProduct(){let id=Number(new URLSearchParams(location.search).get("id"))||1,p=loadData().find(x=>x.id==id)||loadData()[0];let gallery=p.gallery&&p.gallery.length?p.gallery:[p.img];let sizes=p.sizes&&p.sizes.length?p.sizes:["S","M","L","XL","XXL"];document.querySelector("#product").innerHTML=`<div class="product-gallery"><div class="thumbs">${gallery.map((src,i)=>`<button class="thumb ${i===0?"active":""}" onclick="selectProductImage(${i})"><img src="${src}" alt="${p.name} image ${i+1}"></button>`).join("")}</div><div><img id="mainProductImage" class="product-main" src="${gallery[0]}" alt="${p.name}"></div></div><div><div class="muted">${p.cat} / LIGOZZA</div><h1>${p.name}</h1><div class="bigprice">${money(p.price)}</div><p class="muted">${p.desc}</p><h4>Size</h4><div class="chips" id="sizeChoices">${sizes.map((x,i)=>`<button type="button" class="chip ${i===0?"selected":""}" onclick="selectSize(this)">${x}</button>`).join("")}</div><div class="qty"><button onclick="changeProductQty(-1)">−</button><b id="productQty">1</b><button onclick="changeProductQty(1)">+</button></div><div class="actions"><button class="btn" onclick="addProductToCart(${p.id})">Add to Cart</button><a class="btn light" href="cart.html">View Cart</a></div><hr style="border:0;border-top:1px solid #eee;margin:30px 0"><p><b>Product details</b></p><p class="muted">Premium LIGOZZA design • Multiple product photos • Selectable sizes • Easy returns • Secure checkout ready • Sri Lanka delivery.</p></div></div>`;window.currentProductGallery=gallery}
function selectProductImage(i){let g=window.currentProductGallery||[];if(!g[i])return;document.querySelector("#mainProductImage").src=g[i];document.querySelectorAll(".thumb").forEach((b,n)=>b.classList.toggle("active",n===i))}
function selectSize(btn){document.querySelectorAll("#sizeChoices .chip").forEach(x=>x.classList.remove("selected"));btn.classList.add("selected")}
function changeProductQty(n){let e=document.querySelector("#productQty");if(e)e.textContent=Math.max(1,Number(e.textContent)+n)}
function addProductToCart(id){let size=document.querySelector("#sizeChoices .chip.selected")?.textContent.trim()||"One Size";let qty=Number(document.querySelector("#productQty")?.textContent)||1;addToCart(id,size,qty)}
function initShop(){let ps=loadData(),el=document.querySelector("#products"),q=document.querySelector("#q"),cat=document.querySelector("#cat");function go(){let a=ps.filter(p=>(!q.value||p.name.toLowerCase().includes(q.value.toLowerCase()))&&(!cat.value||p.cat==cat.value));renderGrid(a,el)}q?.addEventListener("input",go);cat?.addEventListener("change",go);go()}
function initCategory(){let cat=document.body.dataset.category;renderGrid(loadData().filter(p=>p.cat==cat),document.querySelector("#products"))}
function initHome(){renderGrid(loadData().slice(0,8),document.querySelector("#featured"))}
function initAdmin(){let ps=loadData(),sel=document.querySelector("#editId"),list=document.querySelector("#admin-list");function fill(){let p=ps.find(x=>x.id==+sel.value)||ps[0];document.querySelector("#name").value=p.name;document.querySelector("#price").value=p.price;document.querySelector("#category").value=p.cat;document.querySelector("#desc").value=p.desc;document.querySelector("#img").value=p.img;document.querySelectorAll("#sizes input[type=checkbox]").forEach(c=>c.checked=p.sizes.includes(c.value));document.querySelector("#gallery-list").innerHTML=p.gallery.map((src,i)=>`<div class="gallery-admin-item"><img src="${src}"><span>Image ${i+1}</span><button type="button" class="remove-img" onclick="removeGalleryImage(${i})">Remove</button></div>`).join("")}
window.removeGalleryImage=function(i){let p=ps.find(x=>x.id==+sel.value);if(p.gallery.length<=1){toast("Keep at least one image");return}p.gallery.splice(i,1);p.img=p.gallery[0];saveData(ps);fill();draw()};
sel.innerHTML=ps.map(p=>`<option value="${p.id}">${p.name}</option>`).join("");sel.onchange=fill;fill();document.querySelector("#save").onclick=()=>{let p=ps.find(x=>x.id==+sel.value);p.name=document.querySelector("#name").value;p.price=+document.querySelector("#price").value;p.cat=document.querySelector("#category").value;p.desc=document.querySelector("#desc").value;let selected=[...document.querySelectorAll("#sizes input[type=checkbox]:checked")].map(x=>x.value);p.sizes=selected.length?selected:["One Size"];let files=[...document.querySelector("#files").files];if(files.length){let results=[];let done=0;files.forEach(f=>{let r=new FileReader();r.onload=()=>{results.push(r.result);done++;if(done===files.length){p.gallery=[...p.gallery,...results];p.img=p.gallery[0];saveData(ps);fill();draw();toast(`${files.length} image${files.length>1?"s":""} added`)}};r.readAsDataURL(f)})}else{saveData(ps);draw();toast("Product updated")}};document.querySelector("#addImages").onclick=()=>document.querySelector("#files").click();function draw(){list.innerHTML=ps.map(p=>`<div class="adminitem"><img src="${p.img}"><div><b>${p.name}</b><div class="muted">${p.cat} · ${p.gallery.length} image${p.gallery.length!==1?"s":""} · Sizes: ${p.sizes.join(", ")}</div></div><b>${money(p.price)}</b><button onclick="document.querySelector('#editId').value=${p.id};document.querySelector('#editId').onchange()">Edit</button></div>`).join("")}draw()}
document.addEventListener("DOMContentLoaded",()=>{updateCount();document.querySelector(".hamb")?.addEventListener("click",openDrawer);document.querySelector(".drawer .close")?.addEventListener("click",closeDrawer);if(document.querySelector("#featured"))initHome();if(document.querySelector("#products")&&location.pathname.endsWith("shop.html"))initShop();if(document.body.dataset.category)initCategory();if(document.querySelector("#product"))renderProduct();if(document.querySelector("#cart-list"))renderCart();if(document.querySelector("#editId"))initAdmin()})
